AWSTemplateFormatVersion: 2010-09-09
Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-01aab85a5e4a5a0fe
      InstanceType: t2.micro
      KeyName: cfn-key-2
