AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance.

Parameters:
  keyName:
    Description: ec2 key name
    Type: AWS::EC2::KeyPair::KeyName
  avaialbleZone:
    Description: Avaialble zone
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-2a
    AllowedValues:
      - us-east-2a
      - us-east-2b
      - us-east-2c
  instanceType:
    Description: instance size
    Type: AWS::SSM::Parameter::Value<String>


Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cd3dfa4e37921605
      InstanceType: !Ref instanceType
      KeyName: !Ref keyName
      AvailabilityZone: !Ref avaialbleZone
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8081'
          ToPort: '8081'
          CidrIp: 0.0.0.0/0          
  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DevEC2Instance           